In [1]:
# Import pandas to read the CSV file
import pandas as pd

# Import sqlite3 to create and use a SQLite database
import sqlite3

# Import Path to safely handle file and folder paths on Mac
from pathlib import Path


# Set the main project folder
# This assumes this notebook is inside 03_python_notebooks
project_folder = Path.cwd().parent


# Set the cleaned CSV file path
clean_csv_path = project_folder / "02_cleaned_data" / "Drishti_Clean_Data.csv"


# Set the database file path
db_path = project_folder / "04_sql_database" / "nutricoach.db"


# Print paths so we can check them
print("CSV path:", clean_csv_path)
print("Database path:", db_path)

CSV path: /Users/pari/Desktop/Get_Fit_with_Drishti_BA_Project/02_cleaned_data/Drishti_Clean_Data.csv
Database path: /Users/pari/Desktop/Get_Fit_with_Drishti_BA_Project/04_sql_database/nutricoach.db

In [2]:
# Load the cleaned CSV file into a pandas DataFrame
df = pd.read_csv(clean_csv_path)

# Show the number of rows and columns in the dataset
print("Dataset shape:", df.shape)

# Show the first 5 rows to confirm the data loaded correctly
df.head()

Dataset shape: (3000, 40)

,Client_ID,Age,Gender,Country,City,Diet_Type,Goal_Type,Lead_Source,Referred_By,Health_Condition,...,Progress_Photos_Shared,Goal_Achieved,Returned_After_Drop,Weeks_Before_Return,Return_Trigger,Revenue_USD,Second_Round,Program_Duration_Days,Ever_Engaged,Was_Referred
0,C0001,24,Female,USA,Las Vegas,Vegetarian,Body Transformation,Other,NaN,Thyroid,...,Yes,Partial,NaN,0.0,NaN,300,No,100,True,False
1,C0002,30,Female,USA,Chicago,Non-Vegetarian,Body Transformation,Instagram,NaN,Thyroid,...,Yes,No,No,0.0,NaN,300,No,5,False,False
2,C0003,19,Female,USA,Houston,Non-Vegetarian,Weight Loss,TikTok,NaN,NaN,...,Yes,Partial,NaN,0.0,NaN,300,No,100,True,False
3,C0004,22,Female,Australia,Canberra,Non-Vegetarian,Weight Loss,TikTok,NaN,NaN,...,Yes,Yes,NaN,0.0,NaN,300,No,100,True,False
4,C0005,31,Male,USA,New York,Non-Vegetarian,Weight Loss,TikTok,NaN,NaN,...,No,No,Yes,11.0,Saw Other Clients Progress,300,No,4,True,False

In [3]:
print("Dataset shape:", df.shape)

Dataset shape: (3000, 40)

In [4]:
# Create a connection to the SQLite database
# If nutricoach.db does not already exist, Python will create it automatically
conn = sqlite3.connect(db_path)

# Save the DataFrame as a SQL table named clients
# if_exists="replace" means it will replace the table if it already exists
# index=False means pandas will not add an extra index column
df.to_sql("clients", conn, if_exists="replace", index=False)

# Print confirmation messages
print("SQLite database created successfully.")
print("Table created successfully: clients")

SQLite database created successfully.
Table created successfully: clients

In [5]:
# Write a SQL query to count all rows in the clients table
query = """
SELECT COUNT(*) AS total_rows
FROM clients;
"""

# Run the SQL query using pandas and the SQLite connection
row_count = pd.read_sql_query(query, conn)

# Display the row count result
row_count

   total_rows
0        3000

In [6]:
# Write a SQL query to preview the first 5 rows from the clients table
query = """
SELECT *
FROM clients
LIMIT 5;
"""

# Run the query and display the first 5 rows
preview_table = pd.read_sql_query(query, conn)

# Show the preview
preview_table

,Client_ID,Age,Gender,Country,City,Diet_Type,Goal_Type,Lead_Source,Referred_By,Health_Condition,...,Progress_Photos_Shared,Goal_Achieved,Returned_After_Drop,Weeks_Before_Return,Return_Trigger,Revenue_USD,Second_Round,Program_Duration_Days,Ever_Engaged,Was_Referred
0,C0001,24,Female,USA,Las Vegas,Vegetarian,Body Transformation,Other,None,Thyroid,...,Yes,Partial,NaN,0.0,NaN,300,No,100,1,0
1,C0002,30,Female,USA,Chicago,Non-Vegetarian,Body Transformation,Instagram,None,Thyroid,...,Yes,No,No,0.0,NaN,300,No,5,0,0
2,C0003,19,Female,USA,Houston,Non-Vegetarian,Weight Loss,TikTok,None,NaN,...,Yes,Partial,NaN,0.0,NaN,300,No,100,1,0
3,C0004,22,Female,Australia,Canberra,Non-Vegetarian,Weight Loss,TikTok,None,NaN,...,Yes,Yes,NaN,0.0,NaN,300,No,100,1,0
4,C0005,31,Male,USA,New York,Non-Vegetarian,Weight Loss,TikTok,None,NaN,...,No,No,Yes,11.0,Saw Other Clients Progress,300,No,4,1,0

In [7]:
# Write a SQLite command to check the structure of the clients table
query = """
PRAGMA table_info(clients);
"""

# Run the query and store the table structure
table_structure = pd.read_sql_query(query, conn)

# Display the table structure
table_structure

    cid                       name     type  notnull dflt_value  pk
0     0                  Client_ID     TEXT        0       None   0
1     1                        Age  INTEGER        0       None   0
2     2                     Gender     TEXT        0       None   0
3     3                    Country     TEXT        0       None   0
4     4                       City     TEXT        0       None   0
5     5                  Diet_Type     TEXT        0       None   0
6     6                  Goal_Type     TEXT        0       None   0
7     7                Lead_Source     TEXT        0       None   0
8     8                Referred_By     TEXT        0       None   0
9     9           Health_Condition     TEXT        0       None   0
10   10             Daily_Schedule     TEXT        0       None   0
11   11           Exercise_History     TEXT        0       None   0
12   12                  Height_cm  INTEGER        0       None   0
13   13            Start_Weight_kg  INTEGER        0       None   0
14   14           Target_Weight_kg  INTEGER        0       None   0
15   15                Goal_Gap_kg  INTEGER        0       None   0
16   16               Payment_Date     TEXT        0       None   0
17   17         Payment_Speed_Days  INTEGER        0       None   0
18   18   Days_To_First_Engagement  INTEGER        0       None   0
19   19         Program_Start_Date     TEXT        0       None   0
20   20           Program_End_Date     TEXT        0       None   0
21   21                     Status     TEXT        0       None   0
22   22         Week3_Still_Active     TEXT        0       None   0
23   23                Dropout_Day     REAL        0       None   0
24   24             Dropout_Reason     TEXT        0       None   0
25   25   Weekly_Checkins_Expected  INTEGER        0       None   0
26   26  Weekly_Checkins_Completed  INTEGER        0       None   0
27   27           Checkin_Rate_Pct     REAL        0       None   0
28   28       Daily_Comm_Frequency     TEXT        0       None   0
29   29     Motivation_Level_Start     TEXT        0       None   0
30   30     Progress_Photos_Shared     TEXT        0       None   0
31   31              Goal_Achieved     TEXT        0       None   0
32   32        Returned_After_Drop     TEXT        0       None   0
33   33        Weeks_Before_Return     REAL        0       None   0
34   34             Return_Trigger     TEXT        0       None   0
35   35                Revenue_USD  INTEGER        0       None   0
36   36               Second_Round     TEXT        0       None   0
37   37      Program_Duration_Days  INTEGER        0       None   0
38   38               Ever_Engaged  INTEGER        0       None   0
39   39               Was_Referred  INTEGER        0       None   0

In [8]:
# Close the SQLite database connection
conn.close()

# Print a confirmation message
print("SQLite database connection closed.")

SQLite database connection closed.

In [9]:
# Import Path again in case the notebook session needs it
from pathlib import Path

# Set the main project folder
# This assumes the notebook is inside the 03_python_notebooks folder
project_folder = Path.cwd().parent

# Set the SQL queries folder path
sql_folder = project_folder / "05_sql_queries"

# Create the folder if it does not already exist
sql_folder.mkdir(exist_ok=True)

# Set the full path for the SQL file
sql_file_path = sql_folder / "phase_2_business_analysis_queries.sql"

# Create the SQL file with a starter header
with open(sql_file_path, "w") as file:
    file.write("""-- ============================================================
-- Get Fit with Drishti
-- Phase 2: SQL Business Analysis Queries
-- Database: nutricoach.db
-- Table: clients
-- ============================================================

""")

# Print confirmation
print("SQL file created successfully:")
print(sql_file_path)

SQL file created successfully:
/Users/pari/Desktop/Get_Fit_with_Drishti_BA_Project/05_sql_queries/phase_2_business_analysis_queries.sql

In [10]:
# Import sqlite3 to connect Python with the SQLite database
import sqlite3

# Reconnect to the nutricoach.db database using the database path we created earlier
conn = sqlite3.connect(db_path)

# Print confirmation message
print("Connected to nutricoach.db successfully.")

Connected to nutricoach.db successfully.

In [11]:
# SQL Query 1:Goal Type Breakdown
# This query counts clients by goal type and calculates percentage of total clients

query_1 = """
SELECT 
    Goal_Type,
    COUNT(*) AS client_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total
FROM clients
GROUP BY Goal_Type
ORDER BY client_count DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_1_result = pd.read_sql_query(query_1, conn)

# Display the result
query_1_result

             Goal_Type  client_count  percentage_of_total
0          Weight Loss          1500                50.00
1  Body Transformation           937                31.23
2          Weight Gain           563                18.77

In [12]:
# Save into the SQL file
# "a" means append, so it adds this query without deleting the existing file content

with open(sql_file_path, "a") as file:
    file.write("""
-- Query 1: Goal Type Breakdown
-- Business Question:
-- What are the main client goals, and what percentage of total clients does each goal represent?

SELECT 
    Goal_Type,
    COUNT(*) AS client_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total
FROM clients
GROUP BY Goal_Type
ORDER BY client_count DESC;

""")

# Print confirmation message
print("Query 1 saved to SQL file successfully.")

Query 1 saved to SQL file successfully.

In [13]:
# SQL Query 2:Lead Source Completion Rate
# This query finds the completion rate for each lead source

query_2 = """
SELECT
    Lead_Source,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct
FROM clients
GROUP BY Lead_Source
ORDER BY completion_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_2_result = pd.read_sql_query(query_2, conn)

# Display the result
query_2_result

  Lead_Source  total_clients  completed_clients  completion_rate_pct
0    Referral            772                655                84.84
1       Other            138                111                80.43
2      TikTok           1614               1297                80.36
3   Instagram            476                368                77.31

In [14]:
#  SQL Query 3:Average Check-in Rate by Goal Type and Motivation Level
# This query shows average client engagement across goal type and starting motivation level

query_3 = """
SELECT
    Goal_Type,
    Motivation_Level_Start,
    COUNT(*) AS total_clients,
    ROUND(AVG(Checkin_Rate_Pct), 2) AS avg_checkin_rate_pct
FROM clients
GROUP BY Goal_Type, Motivation_Level_Start
ORDER BY Goal_Type, avg_checkin_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_3_result = pd.read_sql_query(query_3, conn)

# Display the result
query_3_result

,Goal_Type,Motivation_Level_Start,total_clients,avg_checkin_rate_pct
0,Body Transformation,High,555,77.85
1,Body Transformation,Medium,276,75.53
2,Body Transformation,Low,106,73.26
3,Weight Gain,Medium,194,77.22
4,Weight Gain,High,314,75.26
5,Weight Gain,Low,55,59.22
6,Weight Loss,High,882,76.02
7,Weight Loss,Medium,457,74.03
8,Weight Loss,Low,161,63.32

In [15]:
# SQL Query 4: Goal Achievement Rate by Diet Type
# This query compares success rate across different diet types

query_4 = """
SELECT
    Diet_Type,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY Diet_Type
ORDER BY goal_achievement_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_4_result = pd.read_sql_query(query_4, conn)

# Display the result
query_4_result

,Diet_Type,total_clients,goal_achieved_clients,goal_achievement_rate_pct
0,Vegetarian,900,473,52.56
1,Eggetarian,290,149,51.38
2,Non-Vegetarian,1652,835,50.54
3,Vegan,158,79,50.00

In [16]:
# SQL Query 5:Country Breakdown
# This query compares client count, completion rate, and goal achievement rate by country

query_5 = """
SELECT
    Country,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY Country
ORDER BY total_clients DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_5_result = pd.read_sql_query(query_5, conn)

# Display the result
query_5_result

,Country,total_clients,completed_clients,completion_rate_pct,goal_achieved_clients,goal_achievement_rate_pct
0,Australia,1079,871,80.72,576,53.38
1,USA,902,719,79.71,438,48.56
2,Nepal,571,472,82.66,294,51.49
3,UAE,214,178,83.18,103,48.13
4,Canada,144,116,80.56,80,55.56
5,Other,90,75,83.33,45,50.00

In [17]:
# SQL Query 6:Monthly Client Acquisition Trend
# This query counts how many new clients joined each month using Payment_Date

query_6 = """
SELECT
    strftime('%Y-%m', Payment_Date) AS payment_month,
    COUNT(*) AS new_clients
FROM clients
GROUP BY payment_month
ORDER BY payment_month;
"""

# Run the SQL query and store the result in a DataFrame
query_6_result = pd.read_sql_query(query_6, conn)

# Display the result
query_6_result

   payment_month  new_clients
0        2022-01           36
1        2022-02           30
2        2022-03           46
3        2022-04           47
4        2022-05           32
5        2022-06           35
6        2022-07           48
7        2022-08           36
8        2022-09           30
9        2022-10           33
10       2022-11           32
11       2022-12           45
12       2023-01           88
13       2023-02           79
14       2023-03           87
15       2023-04           94
16       2023-05           95
17       2023-06           83
18       2023-07           68
19       2023-08           79
20       2023-09           74
21       2023-10           73
22       2023-11           81
23       2023-12           74
24       2024-01          131
25       2024-02          136
26       2024-03          129
27       2024-04          137
28       2024-05          130
29       2024-06          126
30       2024-07          133
31       2024-08          131
32       2024-09          128
33       2024-10          146
34       2024-11          120
35       2024-12          128

In [18]:
# SQL Query 7:Week 3 Activity and Completion
# This query checks week 3 activity and whether inactive clients eventually completed

query_7 = """
SELECT
    Week3_Still_Active,
    COUNT(*) AS total_clients,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct
FROM clients
GROUP BY Week3_Still_Active
ORDER BY Week3_Still_Active DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_7_result = pd.read_sql_query(query_7, conn)

# Display the result
query_7_result

,Week3_Still_Active,total_clients,percentage_of_total,completed_clients,completion_rate_pct
0,Yes,2677,89.23,2431,90.81
1,No,323,10.77,0,0.00

In [19]:
# SQL Query 8:Second Round Analysis
# This query checks what percentage of completed clients signed up again, grouped by goal type

query_8 = """
SELECT
    Goal_Type,
    COUNT(*) AS completed_clients,
    SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) AS second_round_clients,
    ROUND(
        SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS second_round_rate_pct
FROM clients
WHERE Status = 'Completed'
GROUP BY Goal_Type
ORDER BY second_round_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_8_result = pd.read_sql_query(query_8, conn)

# Display the result
query_8_result

,Goal_Type,completed_clients,second_round_clients,second_round_rate_pct
0,Weight Loss,1198,124,10.35
1,Body Transformation,782,68,8.70
2,Weight Gain,451,37,8.20

In [20]:
# SQL Query 9:Ghost Client Profile
# This query summarizes clients who had 0% check-in rate

query_9 = """
SELECT
    Goal_Type,
    Lead_Source,
    Country,
    COUNT(*) AS ghost_clients,
    ROUND(AVG(Age), 2) AS avg_age
FROM clients
WHERE Checkin_Rate_Pct = 0
GROUP BY Goal_Type, Lead_Source, Country
ORDER BY ghost_clients DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_9_result = pd.read_sql_query(query_9, conn)

# Display the result
query_9_result

              Goal_Type Lead_Source    Country  ghost_clients  avg_age
0           Weight Loss      TikTok  Australia             15    36.40
1   Body Transformation      TikTok  Australia             11    33.27
2           Weight Loss      TikTok        USA             10    31.20
3   Body Transformation    Referral  Australia              9    35.33
4   Body Transformation      TikTok        USA              6    31.17
5           Weight Gain      TikTok  Australia              5    25.60
6           Weight Loss    Referral  Australia              5    34.00
7           Weight Loss      TikTok      Nepal              5    34.40
8           Weight Loss   Instagram        USA              4    33.00
9   Body Transformation   Instagram        USA              3    25.67
10  Body Transformation    Referral        USA              3    23.67
11          Weight Gain   Instagram  Australia              3    35.33
12          Weight Gain      TikTok        UAE              3    35.00
13          Weight Gain      TikTok        USA              3    31.67
14          Weight Loss   Instagram  Australia              3    39.00
15  Body Transformation       Other  Australia              2    50.00
16  Body Transformation    Referral      Other              2    26.50
17  Body Transformation      TikTok      Nepal              2    29.00
18          Weight Gain    Referral  Australia              2    46.50
19          Weight Gain    Referral        USA              2    20.50
20          Weight Loss   Instagram      Nepal              2    24.50
21          Weight Loss       Other      Nepal              2    28.00
22          Weight Loss    Referral        USA              2    33.50
23          Weight Loss      TikTok        UAE              2    40.00
24  Body Transformation   Instagram  Australia              1    28.00
25  Body Transformation   Instagram      Nepal              1    33.00
26  Body Transformation   Instagram        UAE              1    29.00
27  Body Transformation       Other        USA              1    37.00
28  Body Transformation    Referral      Nepal              1    30.00
29  Body Transformation      TikTok     Canada              1    57.00
30  Body Transformation      TikTok      Other              1    20.00
31  Body Transformation      TikTok        UAE              1    29.00
32          Weight Gain   Instagram        USA              1    46.00
33          Weight Gain    Referral      Nepal              1    25.00
34          Weight Gain      TikTok     Canada              1    50.00
35          Weight Gain      TikTok      Nepal              1    35.00
36          Weight Loss   Instagram     Canada              1    35.00
37          Weight Loss       Other  Australia              1    26.00
38          Weight Loss       Other     Canada              1    20.00
39          Weight Loss    Referral     Canada              1    50.00
40          Weight Loss    Referral      Nepal              1    49.00
41          Weight Loss      TikTok     Canada              1    48.00
42          Weight Loss      TikTok      Other              1    40.00

In [21]:
#  SQL Query 10:Payment Speed by Lead Source
# This query compares how fast clients from each lead source convert from first contact to payment

query_10 = """
SELECT
    Lead_Source,
    COUNT(*) AS total_clients,
    ROUND(AVG(Payment_Speed_Days), 2) AS avg_payment_speed_days,
    MIN(Payment_Speed_Days) AS fastest_payment_days,
    MAX(Payment_Speed_Days) AS slowest_payment_days
FROM clients
GROUP BY Lead_Source
ORDER BY avg_payment_speed_days ASC;
"""

# Run the SQL query and store the result in a DataFrame
query_10_result = pd.read_sql_query(query_10, conn)

# Display the result
query_10_result

,Lead_Source,total_clients,avg_payment_speed_days,fastest_payment_days,slowest_payment_days
0,Other,138,2.67,1,14
1,TikTok,1614,2.90,1,14
2,Referral,772,2.94,1,14
3,Instagram,476,3.18,1,14

In [22]:
# SQL Query 11:Health Condition vs Healthy Clients
# This query compares clients with health conditions against clients without health conditions

query_11 = """
SELECT
    CASE 
        WHEN Health_Condition = 'N/A' THEN 'No Health Condition'
        ELSE 'Has Health Condition'
    END AS health_group,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY health_group
ORDER BY total_clients DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_11_result = pd.read_sql_query(query_11, conn)

# Display the result
query_11_result

,health_group,total_clients,completed_clients,completion_rate_pct,goal_achieved_clients,goal_achievement_rate_pct
0,Has Health Condition,3000,2431,81.03,1536,51.2

In [23]:
# SQL Query 11:Check all unique Health_Condition values and their counts
# This helps us see how "no health condition" is stored in the database

health_check_query = """
SELECT
    Health_Condition,
    COUNT(*) AS total_clients
FROM clients
GROUP BY Health_Condition
ORDER BY total_clients DESC;
"""

# Run the SQL query
health_check_result = pd.read_sql_query(health_check_query, conn)

# Display the result
health_check_result

  Health_Condition  total_clients
0              NaN           1931
1             PCOS            330
2          Thyroid            250
3        Back Pain            217
4         Diabetes            169
5            Other            103

In [25]:
# SQL Query 11: Health Condition vs Healthy Clients
# This corrected query uses IS NULL because no health condition is stored as missing/NaN

query_11 = """
SELECT
    CASE 
        WHEN Health_Condition IS NULL THEN 'No Health Condition'
        ELSE 'Has Health Condition'
    END AS health_group,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY health_group
ORDER BY total_clients DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_11_result = pd.read_sql_query(query_11, conn)

# Display the result
query_11_result

,health_group,total_clients,completed_clients,completion_rate_pct,goal_achieved_clients,goal_achievement_rate_pct
0,No Health Condition,1931,1570,81.31,999,51.73
1,Has Health Condition,1069,861,80.54,537,50.23

In [27]:
# SQL Query 11: Health Condition vs Healthy Clients
# This corrected query uses IS NULL because no health condition is stored as missing/NaN

query_11 = """
SELECT
    CASE 
        WHEN Health_Condition IS NULL THEN 'No Health Condition'
        ELSE 'Has Health Condition'
    END AS health_group,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY health_group
ORDER BY total_clients DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_11_result = pd.read_sql_query(query_11, conn)

# Display the result
query_11_result

,health_group,total_clients,completed_clients,completion_rate_pct,goal_achieved_clients,goal_achievement_rate_pct
0,No Health Condition,1931,1570,81.31,999,51.73
1,Has Health Condition,1069,861,80.54,537,50.23

In [28]:
# SQL Query 12: Win-back Analysis
# This query analyzes dropout clients and checks how many returned after dropping out

query_12 = """
SELECT
    Dropout_Reason,
    COUNT(*) AS dropout_clients,
    SUM(CASE WHEN Returned_After_Drop = 'Yes' THEN 1 ELSE 0 END) AS returned_clients,
    ROUND(
        SUM(CASE WHEN Returned_After_Drop = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS return_rate_pct,
    ROUND(AVG(Weeks_Before_Return), 2) AS avg_weeks_before_return
FROM clients
WHERE Dropout_Reason IS NOT NULL
GROUP BY Dropout_Reason
ORDER BY return_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_12_result = pd.read_sql_query(query_12, conn)

# Display the result
query_12_result

,Dropout_Reason,dropout_clients,returned_clients,return_rate_pct,avg_weeks_before_return
0,Health Issue,7,7,100.00,9.14
1,Busy Schedule,41,32,78.05,7.49
2,Laziness,22,14,63.64,4.36

In [29]:
# SQL Query 13: Referral Value
# This query compares referred clients vs non-referred clients

query_13 = """
SELECT
    CASE
        WHEN Referred_By IS NULL THEN 'Non-Referred Client'
        ELSE 'Referred Client'
    END AS referral_group,
    COUNT(*) AS total_clients,
    ROUND(AVG(Revenue_USD), 2) AS avg_revenue_usd,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) AS second_round_clients,
    ROUND(
        SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS second_round_rate_pct
FROM clients
GROUP BY referral_group
ORDER BY completion_rate_pct DESC;
"""

# Run the SQL query and store the result in a DataFrame
query_13_result = pd.read_sql_query(query_13, conn)

# Display the result
query_13_result

,referral_group,total_clients,avg_revenue_usd,completed_clients,completion_rate_pct,second_round_clients,second_round_rate_pct
0,Referred Client,772,286.40,655,84.84,274,35.49
1,Non-Referred Client,2228,285.49,1776,79.71,154,6.91

In [30]:
# Save all 13 finalized SQL queries into one clean .sql file
# This will overwrite the existing file and create the final organized SQL query file

all_sql_queries = """
-- ============================================================
-- Get Fit with Drishti
-- Phase 2: SQL Business Analysis Queries
-- Database: nutricoach.db
-- Table: clients
-- ============================================================


-- Query 1: Goal Type Breakdown
-- Business Question:
-- What are the main client goals, and what percentage of total clients does each goal represent?

SELECT 
    Goal_Type,
    COUNT(*) AS client_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total
FROM clients
GROUP BY Goal_Type
ORDER BY client_count DESC;



-- Query 2: Lead Source Completion Rate
-- Business Question:
-- Which lead source brings clients with the highest completion rate?

SELECT
    Lead_Source,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct
FROM clients
GROUP BY Lead_Source
ORDER BY completion_rate_pct DESC;



-- Query 3: Average Check-in Rate by Goal Type and Motivation Level
-- Business Question:
-- Which goal and motivation groups have the highest or lowest check-in engagement?

SELECT
    Goal_Type,
    Motivation_Level_Start,
    COUNT(*) AS total_clients,
    ROUND(AVG(Checkin_Rate_Pct), 2) AS avg_checkin_rate_pct
FROM clients
GROUP BY Goal_Type, Motivation_Level_Start
ORDER BY Goal_Type, avg_checkin_rate_pct DESC;



-- Query 4: Goal Achievement Rate by Diet Type
-- Business Question:
-- Does diet type appear to affect client success?

SELECT
    Diet_Type,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY Diet_Type
ORDER BY goal_achievement_rate_pct DESC;



-- Query 5: Country Breakdown
-- Business Question:
-- Which countries bring the most clients, and how successful are clients from each country?

SELECT
    Country,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY Country
ORDER BY total_clients DESC;



-- Query 6: Monthly Client Acquisition Trend
-- Business Question:
-- How many new clients joined each month?

SELECT
    strftime('%Y-%m', Payment_Date) AS payment_month,
    COUNT(*) AS new_clients
FROM clients
GROUP BY payment_month
ORDER BY payment_month;



-- Query 7: Week 3 Activity and Completion
-- Business Question:
-- Is week 3 activity a strong early warning signal for program completion?

SELECT
    Week3_Still_Active,
    COUNT(*) AS total_clients,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct
FROM clients
GROUP BY Week3_Still_Active
ORDER BY Week3_Still_Active DESC;



-- Query 8: Second Round Analysis
-- Business Question:
-- Which completed client goal group is most likely to sign up again?

SELECT
    Goal_Type,
    COUNT(*) AS completed_clients,
    SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) AS second_round_clients,
    ROUND(
        SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS second_round_rate_pct
FROM clients
WHERE Status = 'Completed'
GROUP BY Goal_Type
ORDER BY second_round_rate_pct DESC;



-- Query 9: Ghost Client Profile
-- Business Question:
-- Who are the clients most likely to disappear without checking in?

SELECT
    Goal_Type,
    Lead_Source,
    Country,
    COUNT(*) AS ghost_clients,
    ROUND(AVG(Age), 2) AS avg_age
FROM clients
WHERE Checkin_Rate_Pct = 0
GROUP BY Goal_Type, Lead_Source, Country
ORDER BY ghost_clients DESC;



-- Query 10: Payment Speed by Lead Source
-- Business Question:
-- Which lead source converts clients from first contact to payment the fastest?

SELECT
    Lead_Source,
    COUNT(*) AS total_clients,
    ROUND(AVG(Payment_Speed_Days), 2) AS avg_payment_speed_days,
    MIN(Payment_Speed_Days) AS fastest_payment_days,
    MAX(Payment_Speed_Days) AS slowest_payment_days
FROM clients
GROUP BY Lead_Source
ORDER BY avg_payment_speed_days ASC;



-- Query 11: Health Condition vs Healthy Clients
-- Business Question:
-- Do clients with health conditions perform differently from clients without health conditions?

SELECT
    CASE 
        WHEN Health_Condition IS NULL THEN 'No Health Condition'
        ELSE 'Has Health Condition'
    END AS health_group,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) AS goal_achieved_clients,
    ROUND(
        SUM(CASE WHEN Goal_Achieved = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS goal_achievement_rate_pct
FROM clients
GROUP BY health_group
ORDER BY total_clients DESC;



-- Query 12: Win-back Analysis
-- Business Question:
-- Which dropout reasons are most likely to turn into successful win-backs?

SELECT
    Dropout_Reason,
    COUNT(*) AS dropout_clients,
    SUM(CASE WHEN Returned_After_Drop = 'Yes' THEN 1 ELSE 0 END) AS returned_clients,
    ROUND(
        SUM(CASE WHEN Returned_After_Drop = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS return_rate_pct,
    ROUND(AVG(Weeks_Before_Return), 2) AS avg_weeks_before_return
FROM clients
WHERE Dropout_Reason IS NOT NULL
GROUP BY Dropout_Reason
ORDER BY return_rate_pct DESC;



-- Query 13: Referral Value
-- Business Question:
-- Are referred clients more valuable than non-referred clients?

SELECT
    CASE
        WHEN Referred_By IS NULL THEN 'Non-Referred Client'
        ELSE 'Referred Client'
    END AS referral_group,
    COUNT(*) AS total_clients,
    ROUND(AVG(Revenue_USD), 2) AS avg_revenue_usd,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct,
    SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) AS second_round_clients,
    ROUND(
        SUM(CASE WHEN Second_Round = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS second_round_rate_pct
FROM clients
GROUP BY referral_group
ORDER BY completion_rate_pct DESC;
"""

# Write all final SQL queries into the .sql file
with open(sql_file_path, "w") as file:
    file.write(all_sql_queries)

# Print confirmation message
print("All 13 SQL queries saved successfully.")
print("File location:", sql_file_path)

All 13 SQL queries saved successfully.
File location: /Users/pari/Desktop/Get_Fit_with_Drishti_BA_Project/05_sql_queries/phase_2_business_analysis_queries.sql

In [31]:
# Open the saved SQL file and read its content
with open(sql_file_path, "r") as file:
    saved_sql_content = file.read()

# Print the first 1000 characters to confirm the file saved correctly
print(saved_sql_content[:1000])

-- ============================================================
-- Get Fit with Drishti
-- Phase 2: SQL Business Analysis Queries
-- Database: nutricoach.db
-- Table: clients
-- ============================================================


-- Query 1: Goal Type Breakdown
-- Business Question:
-- What are the main client goals, and what percentage of total clients does each goal represent?

SELECT
    Goal_Type,
    COUNT(*) AS client_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clients), 2) AS percentage_of_total
FROM clients
GROUP BY Goal_Type
ORDER BY client_count DESC;



-- Query 2: Lead Source Completion Rate
-- Business Question:
-- Which lead source brings clients with the highest completion rate?

SELECT
    Lead_Source,
    COUNT(*) AS total_clients,
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_clients,
    ROUND(
        SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_pct
FR